name: Update Submodule

on:
  repository_dispatch:
    types: [update]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Add workspace to safe.directory
        run: git config --global --add safe.directory /github/workspace
      - name: Update submodule
        run: |
          git submodule update --remote ./src/content/markdown/
      - name: Git commit
        run: |
          git config --local user.name "miiimooomiii"
          git config --local user.email "miiimooomiii@pm.me"
          git add -A
          git status
          git commit -m "update submodule (by update_submodule.yml)"
      - name: Git push
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
